fun main() {
//    testMinHeap()
    testMaxHeap()
}

fun testMinHeap() {
    var heap = MinHeap(10)
    println(heap.print())
    heap.insert(10)
    heap.insert(5)
    heap.insert(2)
    heap.insert(15)
    heap.insert(20)
    heap.insert(30)
    heap.insert(25)
    heap.insert(35)
    heap.insert(40)
    heap.insert(50)
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o menor valor: ${heap.remove()}")
    println(heap.print())
}

fun testMaxHeap() {
    var heap = MaxHeap(10)
    println(heap.print())
    heap.insert(10)
    heap.insert(5)
    heap.insert(2)
    heap.insert(15)
    heap.insert(20)
    heap.insert(30)
    heap.insert(25)
    heap.insert(35)
    heap.insert(40)
    heap.insert(50)
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
    println("___________________________")
    println("Removendo o maior valor: ${heap.remove()}")
    println(heap.print())
}